const data = [
  {
    class: "CS 4th sem A",
    subject_teacher: [
      {
        subCode: "HU410",
        teacherName: "Prof. Lakshith",
        credits: 2,
        isLab: false,
        startSlot: "",
      },
      {
        subCode: "MA410",
        teacherName: "Prof. Sujatha Raju",
        credits: 4,
        isLab: false,
        startSlot: "",
      },
      {
        subCode: "CS410",
        teacherName: "Prof. Vani Ashok",
        credits: 4,
        isLab: false,
        startSlot: "",
      },
      {
        subCode: "CS420",
        teacherName: "Prof. Varsha V",
        credits: 4,
        isLab: false,
        startSlot: "",
      },
      {
        subCode: "CS430",
        teacherName: "Prof. H D Nandeesh",
        credits: 3,
        isLab: false,
        startSlot: "",
      },
      {
        subCode: "CS440",
        teacherName: "Prof. S Brunda",
        credits: 4,
        isLab: false,
        startSlot: "",
      },
      {
        subCode: "CS450",
        teacherName: "Prof. Sheela N",
        credits: 4,
        isLab: false,
        startSlot: "",
      },
      {
        subCode: "CS46L",
        teacherName: "",
        credits: "",
        isLab: true,
        startSlot: 39,
      },
      {
        subCode: "CS47L",
        teacherName: "",
        credits: "",
        isLab: true,
        startSlot: 45,
      },
    ],
  },
  {
    class: "CS 4th sem B",
    subject_teacher: [
      {
        subCode: "HU410",
        teacherName: "Prof. Lakshith",
        credits: 2,
        isLab: false,
        startSlot: "",
      },
      {
        subCode: "MA410",
        teacherName: "Prof. Sujatha Raju",
        credits: 4,
        isLab: false,
        startSlot: "",
      },
      {
        subCode: "CS410",
        teacherName: "Dr.A M Chandashekhar",
        credits: 4,
        isLab: false,
        startSlot: "",
      },
      {
        subCode: "CS420",
        teacherName: "Dr. R Guru",
        credits: 4,
        isLab: false,
        startSlot: "",
      },
      {
        subCode: "CS430",
        teacherName: "Prof. Divakara N",
        credits: 3,
        isLab: false,
        startSlot: "",
      },
      {
        subCode: "CS440",
        teacherName: "Prof. ParashivaMurthy B M",
        credits: 4,
        isLab: false,
        startSlot: "",
      },
      {
        subCode: "CS450",
        teacherName: "Prof. Vaniashok",
        credits: 4,
        isLab: false,
        startSlot: "",
      },
      {
        subCode: "CS46L",
        teacherName: "",
        credits: "",
        isLab: true,
        startSlot: 0,
      },
      {
        subCode: "CS47L",
        teacherName: "",
        credits: "",
        isLab: true,
        startSlot: 12,
      },
    ],
  },
  {
    class: "CS 4th sem C",
    subject_teacher: [
      {
        subCode: "HU410",
        teacherName: "Prof. Lakshith",
        credits: 2,
        isLab: false,
        startSlot: "",
      },
      {
        subCode: "MA410",
        teacherName: "Prof. Sujatha Raju",
        credits: 4,
        isLab: false,
        startSlot: "",
      },
      {
        subCode: "CS410",
        teacherName: "Dr. Madhusudhan G",
        credits: 4,
        isLab: false,
        startSlot: "",
      },
      {
        subCode: "CS420",
        teacherName: "Dr. M A Anusuya",
        credits: 4,
        isLab: false,
        startSlot: "",
      },
      {
        subCode: "CS430",
        teacherName: "Dr. Anil Kumar K M",
        credits: 3,
        isLab: false,
        startSlot: "",
      },
      {
        subCode: "CS440",
        teacherName: "Dr. Manimala S",
        credits: 4,
        isLab: false,
        startSlot: "",
      },
      {
        subCode: "CS450",
        teacherName: "Prof. Sheela N",
        credits: 4,
        isLab: false,
        startSlot: "",
      },
      {
        subCode: "CS46L",
        teacherName: "",
        credits: "",
        isLab: true,
        startSlot: 3,
      },
      {
        subCode: "CS47L",
        teacherName: "",
        credits: "",
        isLab: true,
        startSlot: 12,
      },
    ],
  },
  {
    class: "CS 6th sem A",
    subject_teacher: [
      {
        subCode: "CS610",
        teacherName: "Dr. PM Shivamurthy",
        credits: 4,
        isLab: false,
        startSlot: "",
      },
      {
        subCode: "CS620",
        teacherName: "Dr. TrisiladeviCNagavi",
        credits: 3,
        isLab: false,
        startSlot: "",
      },
      {
        subCode: "CS630",
        teacherName: "Dr. S Manjula",
        credits: 4,
        isLab: false,
        startSlot: "",
      },
      {
        subCode: "CS640",
        teacherName: "Dr. B T Prasanna",
        credits: 3,
        isLab: false,
        startSlot: "",
      },
      {
        subCode: "CS652",
        teacherName: "Prof. Ashritha R Murthy",
        credits: 4,
        isLab: false,
        startSlot: "",
      },
      {
        subCode: "CS654",
        teacherName: "Prof. K C Shalini",
        credits: 4,
        isLab: false,
        startSlot: "",
      },
      {
        subCode: "CS661",
        teacherName: "Dr. M P Pushpalatha",
        credits: 2,
        isLab: false,
        startSlot: "",
      },
      {
        subCode: "CS662",
        teacherName: "Prof. Shruthi N M",
        credits: 2,
        isLab: false,
        startSlot: "",
      },
      {
        subCode: "CS665",
        teacherName: "Dr. TrisiladeviC Nagavi",
        credits: 2,
        isLab: false,
        startSlot: "",
      },
      {
        subCode: "CS667L",
        teacherName: "",
        credits: "",
        isLab: true,
        startSlot: 18,
      },
      {
        subCode: "CS668L",
        teacherName: "",
        credits: "",
        isLab: true,
        startSlot: 48,
      },
    ],
  },
  {
    class: "CS 6th sem B",
    subject_teacher: [
      {
        subCode: "CS610",
        teacherName: "Prof. SwethaShree G C",
        credits: 4,
        isLab: false,
        startSlot: "",
      },
      {
        subCode: "CS620",
        teacherName: "Prof. K S Mahesh",
        credits: 3,
        isLab: false,
        startSlot: "",
      },
      {
        subCode: "CS630",
        teacherName: "Prof. Varsha V",
        credits: 4,
        isLab: false,
        startSlot: "",
      },
      {
        subCode: "CS640",
        teacherName: "Dr. B T Prasanna",
        credits: 3,
        isLab: false,
        startSlot: "",
      },
      {
        subCode: "CS652",
        teacherName: "Prof. Ashritha R Murthy",
        credits: 4,
        isLab: false,
        startSlot: "",
      },
      {
        subCode: "CS654",
        teacherName: "Prof. M B Vijay",
        credits: 4,
        isLab: false,
        startSlot: "",
      },
      {
        subCode: "CS661",
        teacherName: "Dr. M P Pushpalatha",
        credits: 2,
        isLab: false,
        startSlot: "",
      },
      {
        subCode: "CS662",
        teacherName: "Prof. Nandeesh",
        credits: 2,
        isLab: false,
        startSlot: "",
      },
      {
        subCode: "CS665",
        teacherName: "Dr. TrisiladeviC Nagavi",
        credits: 2,
        isLab: false,
        startSlot: "",
      },
      {
        subCode: "CS667L",
        teacherName: "",
        credits: "",
        isLab: true,
        startSlot: 9,
      },
      {
        subCode: "CS668L",
        teacherName: "",
        credits: "",
        isLab: true,
        startSlot: 42,
      },
    ],
  },
  {
    class: "CS 6th sem C",
    subject_teacher: [
      {
        subCode: "CS610",
        teacherName: "Prof. ShwethaShree G C",
        credits: 4,
        isLab: false,
        startSlot: "",
      },
      {
        subCode: "CS620",
        teacherName: "Prof. Shruthi N M",
        credits: 3,
        isLab: false,
        startSlot: "",
      },
      {
        subCode: "CS630",
        teacherName: "Dr. S Manjula",
        credits: 4,
        isLab: false,
        startSlot: "",
      },
      {
        subCode: "CS640",
        teacherName: "Prof. Swetha P M",
        credits: 3,
        isLab: false,
        startSlot: "",
      },
      {
        subCode: "CS652",
        teacherName: "Prof. Ashritha R Murthy",
        credits: 4,
        isLab: false,
        startSlot: "",
      },
      {
        subCode: "CS654",
        teacherName: "Prof. Rakshith P",
        credits: 4,
        isLab: false,
        startSlot: "",
      },
      {
        subCode: "CS661",
        teacherName: "Dr. M P Pushpalatha",
        credits: 2,
        isLab: false,
        startSlot: "",
      },
      {
        subCode: "CS662",
        teacherName: "Prof. Shruthi N M",
        credits: 2,
        isLab: false,
        startSlot: "",
      },
      {
        subCode: "CS665",
        teacherName: "Dr. TrisiladeviC Nagavi",
        credits: 2,
        isLab: false,
        startSlot: "",
      },
      {
        subCode: "CS667L",
        teacherName: "",
        credits: "",
        isLab: true,
        startSlot: 24,
      },
      {
        subCode: "CS668L",
        teacherName: "",
        credits: "",
        isLab: true,
        startSlot: 33,
      },
    ],
  },
];

module.exports = { data };
